# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./functions/kustomize-transformer-generator
    binary: kustomize-transformer-generator
    id: kustomize-transformer-generator
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./functions/kustomize-transformer
    binary: kustomize-transformer
    id: kustomize-transformer

# .goreleaser.yaml
archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/kuberik/kpt-fn/kustomize-transformer-generator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/kuberik/kpt-fn/kustomize-transformer-generator:latest"
    build_flag_templates:
      - "--build-arg=binary=kustomize-transformer-generator"
    ids:
      - kustomize-transformer-generator
  - image_templates:
      - "ghcr.io/kuberik/kpt-fn/kustomize-transformer:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/kuberik/kpt-fn/kustomize-transformer:latest"
    build_flag_templates:
      - "--build-arg=binary=kustomize-transformer"
    ids:
      - kustomize-transformer
