apiVersion: v1
kind: ConfigMap
metadata:
  name: transform
  annotations:
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/kuberik/kpt-fn/kustomize-transformer-generator:v0.0.0
        mounts:
          - src: ./internal
            dst: /resources
            type: bind
