name: Publish

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    strategy:
      matrix:
        helm_version: [3.15, 3.16]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6

      - id: get_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - run: >-
          export VERSION=${{ steps.get_version.outputs.version }}-helm-${{ matrix.helm_version }};
          KO_DOCKER_REPO=ghcr.io/kuberik/kpt-fn/kustomize-transformer-generator
          ko build --bare ./functions/kustomize-transformer-generator --tags latest,${VERSION}
      - run: >-
          export VERSION=${{ steps.get_version.outputs.version }}-helm-${{ matrix.helm_version }};
          KO_DEFAULTBASEIMAGE=alpine/helm:${{ matrix.helm_version }}
          KO_DOCKER_REPO=ghcr.io/kuberik/kpt-fn/kustomize-transformer
          ko build --bare ./functions/kustomize-transformer --tags latest,${VERSION}
